name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with LFS files)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup git + LFS
        run: |
          git lfs install --local
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Optional: sanity output (helps confirm nothing under Code/Model_Deployment is tracked anymore)
      - name: Show LFS tracking
        run: git lfs track

      # <<< The setting you asked for >>>
      - name: Allow incomplete LFS push (safe if latest commit needs none)
        run: git config lfs.allowincompletepush true

      # Push HEAD of your GitHub repo to the Space's main branch
      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main
          # If histories are unrelated the first time, uncomment the line below instead:
          # git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
