name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true

      - name: Materialize LFS blobs (ensure real files, not pointers)
        run: |
          git lfs install --local
          git lfs pull
          # sanity print (optional)
          git lfs ls-files --size

      - name: Configure bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Orphan snapshot so the Space has ONLY the current tree (no old history)
      - name: Create orphan deploy snapshot (keep LFS filters)
        run: |
          git checkout --orphan space-deploy
          git add -A
          git commit -m "Space deploy snapshot (with LFS)"

      - name: Push snapshot to Space (force overwrite)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
