name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true # pulls LFS pointers + files
          fetch-depth: 0

      - name: Install Git LFS
        run: git lfs install --local

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push "https://HF_USERNAME:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio" main

