name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Materialize LFS files
        run: |
          git lfs install --local
          # make sure we have the real binaries, not 132B pointers
          git lfs fetch --all
          git lfs checkout  # or: git lfs pull

      - name: Build deploy snapshot (copy real files, strip LFS rules)
        run: |
          rm -rf hf_deploy && mkdir hf_deploy
          rsync -a --exclude '.git' --exclude '.github' ./ hf_deploy/

          # Remove LFS filters so Space stores regular files
          if [ -f hf_deploy/.gitattributes ]; then
            sed -i '/filter=lfs/d' hf_deploy/.gitattributes || true
            [ -s hf_deploy/.gitattributes ] || rm -f hf_deploy/.gitattributes
          fi

          cd hf_deploy
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "HF Space deploy snapshot (real binaries, no LFS)"

      - name: Push snapshot to Space (force overwrite)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_deploy
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
