name: Sync to Hugging Face branch

on:
  push:
    branches: [ main ]   # whenever you push to main

jobs:
  make-hf-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepend HF YAML to README
        run: |
          cat > .hf_header.yml <<'EOF'
          ---
          title: Fin-ML-Studio
          emoji: 📈
          sdk: streamlit
          app_file: app.py
          pinned: false
          tags:
            - streamlit
            - banking/ finance
            - ml
          ---
          EOF
          # Build HF README (YAML + your clean README)
          cat .hf_header.yml README.md > README.hf.md

      - name: Create workspace for hf branch
        run: |
          rm -rf .hf-tmp
          mkdir -p .hf-tmp
          rsync -a --exclude '.git' ./ .hf-tmp/
          mv README.hf.md .hf-tmp/README.md

      - name: Commit & push to hf branch
        run: |
          cd .hf-tmp
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b hf
          git add -A
          git commit -m "Sync from main with HF YAML header"
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git push -f origin hf   # overwrite hf branch with new state
