name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no need to pull old LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Configure bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Create a brand-new history (orphan) that only contains the CURRENT tree
      - name: Create orphan deploy snapshot
        run: |
          git checkout --orphan space-deploy
          git add -A
          git commit -m "HF Space deploy snapshot (no history, no old LFS)"

      - name: Push snapshot to Space (force overwrite Space history)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
