name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false   # no need for LFS in the Space anymore

      - name: Build deploy snapshot (exclude models)
        run: |
          rm -rf hf_deploy && mkdir hf_deploy
          rsync -a \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'Models/**' \
            --exclude 'Code/Model_Deployment/**' \
            ./ hf_deploy/

          # Strip LFS rules so Space stores regular files only
          if [ -f hf_deploy/.gitattributes ]; then
            sed -i '/filter=lfs/d' hf_deploy/.gitattributes || true
            [ -s hf_deploy/.gitattributes ] || rm -f hf_deploy/.gitattributes
          fi

          cd hf_deploy
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "HF Space deploy snapshot (no models)"

      - name: Push snapshot to Space (force overwrite)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_deploy
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
