name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with LFS files)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true     # fetch real LFS files (images, notebooks, etc.)

      - name: Setup git + LFS (local)
        run: |
          git lfs install --local
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # (optional) sanity check: show current LFS patterns after your 'untrack'
      - name: Show LFS tracking
        run: git lfs track

      # Push your current branch HEAD to the Space's main branch
      # Use --force the FIRST time if the Space history is unrelated
      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main
          # If histories are unrelated on first run, use:
          # git push https://Alex-Mak-MCW:${HF_TOKEN}@huggingface.co/spaces/Alex-Mak-MCW/FinML-Studio.git HEAD:main --force
